{
 "title": "Layer Statistics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "SERVER",
    "query": "SELECT id as __value, trim(leading '[ASG] Asgard Eternal | ' from name) as __text\nFROM DBLog_Servers"
   }
  ]
 },
 "panels": [
  {
   "title": "Layer Info",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT layer, winner as \"faction\", ((wins / matchcnt) * 100) as \"win percent\", wins as \"number of wins\", matchcnt as \"number of matches\"\nFROM (SELECT layer, winner, count(*) AS \"wins\",\n       (\n           SELECT count(*)\n           FROM (\n                SELECT mat.id, mat.layerClassname, mat.map, mat.layer, mat.startTime, mat.endTime, mat.winner, mat.server,\n                  (select avg(pc.players)\n                from DBLog_PlayerCounts as pc\n                where\n                    pc.`match`=mat.id\n                ) as playercnt\n                from DBLog_Matches as mat\n           ) as mcdbm\n           WHERE\n               mcdbm.layer = dbm.layer and\n               playercnt>50\n           GROUP BY mcdbm.layer\n           ) as \"matchcnt\"\nFROM (\n                SELECT mat.id, mat.layerClassname, mat.map, mat.layer, mat.startTime, mat.endTime, mat.winner, mat.server,\n                  (select avg(pc.players)\n                from DBLog_PlayerCounts as pc\n                where\n                    pc.`match`=mat.id\n                ) as playercnt\n                from DBLog_Matches as mat\n           ) as dbm\nWHERE\n    dbm.layer IS NOT NULL AND\n    dbm.winner IS NOT NULL AND\n    not dbm.map=\"Jensen\\'s\" and\n    not dbm.layerClassname REGEXP \".*_Seed_.*\" and\n    playercnt>50 and\n    dbm.server = $SERVER\nGROUP BY layer, winner\nORDER BY wins desc) AS winraw\nORDER BY `win percent` DESC, `number of matches` DESC"
    }
   ]
  },
  {
   "title": "Maps Played",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT dbmat.map, count(*) as \"matches\"\nFROM (\n                SELECT mat.id, mat.layerClassname, mat.map, mat.layer, mat.startTime, mat.endTime, mat.winner, mat.server,\n                  (select avg(pc.players)\n                from DBLog_PlayerCounts as pc\n                where\n                    pc.`match`=mat.id\n                ) as playercnt\n                from DBLog_Matches as mat\n           ) as dbmat\nwhere\n    layer is not null and\n    winner is not null and\n    not map=\"Jensen\\'s\" AND\n    not layerClassname regexp \".*_Seed_.*\" and\n    playercnt>50 and\n    server = $SERVER\ngroup by map\norder by matches"
    }
   ]
  },
  {
   "title": "average lengths",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 4, "y": 13 },
   "targets": [
    {
     "rawSql": "select layer, substring_index(substring_index(layerClassname,'_',2),'_',-1) as gamemode,avg(time_to_sec(timediff(endTime, startTime)))/3600 as avgTime\nfrom (SELECT mat.id, mat.layerClassname, mat.map, mat.layer, mat.startTime, mat.endTime, mat.winner, mat.server,\n  (select avg(pc.players)\n    from DBLog_PlayerCounts as pc\n    where\n      pc.`match`=mat.id\n  ) as playercnt\nfrom DBLog_Matches as mat where mat.layer is not null) as mt\nwhere playercnt > 50 and server = $SERVER\ngroup by layer\norder by avgTime desc"
    }
   ]
  },
  {
   "title": "average lengths",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 11, "y": 13 },
   "targets": [
    {
     "rawSql": "select substring_index(substring_index(layerClassname,'_',2),'_',-1) as gamemode,avg(time_to_sec(timediff(endTime, startTime)))/3600 as avgTime\nfrom (SELECT mat.id, mat.layerClassname, mat.map, mat.layer, mat.startTime, mat.endTime, mat.winner, mat.server,\n  (select avg(pc.players)\n    from DBLog_PlayerCounts as pc\n    where\n      pc.`match`=mat.id\n  ) as playercnt\nfrom DBLog_Matches as mat where mat.layer is not null) as mt\nwhere playercnt > 50 and server = $SERVER and layerClassname not regexp \"Seed\"\ngroup by gamemode\norder by avgTime desc"
    }
   ]
  }
 ]
}