{
 "title": "Match info",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "SERVER",
    "label": "Server Name",
    "query": "SELECT id as __value, trim(leading '[ASG] Asgard Eternal | ' from name) as __text\nFROM DBLog_Servers"
   },
   {
    "name": "MATCH",
    "label": "Match ID",
    "query": "SELECT dbmat.id\nFROM (\n                SELECT mat.id, mat.layerClassname, mat.map, mat.layer, mat.startTime, mat.endTime, mat.winner, mat.server,\n                  (select avg(pc.players)\n                from DBLog_PlayerCounts as pc\n                where\n                    pc.`match`=mat.id\n                ) as playercnt\n                from DBLog_Matches as mat\n           ) as dbmat\nWHERE server=$SERVER and playercnt>50 and winner is not null;"
   }
  ]
 },
 "panels": [
  {
   "title": "Match Details",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT startTime, map, layer, time_to_sec(timediff(endTime, startTime))/3600 as Length,\n       (SELECT AVG(players)\n        FROM DBLog_PlayerCounts as pc\n        WHERE\n            pc.`server` = $SERVER  AND\n            pc.`match` = $MATCH) as \"player count\",\n       (SELECT AVG(publicQueue)\n        FROM DBLog_PlayerCounts as pc\n        WHERE\n            pc.`server` = $SERVER  AND\n            pc.`match` = $MATCH) as \"queue count\",\n       winner\nFROM DBLog_Matches\nWHERE\n`server` = $SERVER AND\n`id` = $MATCH"
    }
   ]
  },
  {
   "title": "Match Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Revives",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "rawSql": "SELECT COUNT(*) AS \"Team 1\"\nFROM DBLog_Revives\nWHERE \n`server` = $SERVER AND\n`match` = $MATCH AND\nvictimTeamID = 1;"
      },
      {
       "rawSql": "SELECT COUNT(*) AS \"Team 2\"\nFROM DBLog_Revives\nWHERE \n`server` = $SERVER AND\n`match` = $MATCH AND\nvictimTeamID = 2;"
      }
     ]
    },
    {
     "title": "Wounded",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "rawSql": "SELECT COUNT(*) AS \"Team 1\"\nFROM DBLog_Wounds\nWHERE \n`server` = $SERVER AND\n`match` = $MATCH AND\nteamkill = 0 AND\nvictimTeamID = 1;"
      },
      {
       "rawSql": "SELECT COUNT(*) AS \"Team 2\"\nFROM DBLog_Wounds\nWHERE \n`server` = $SERVER AND\n`match` = $MATCH AND\nteamkill = 0 AND\nvictimTeamID = 2;"
      }
     ]
    },
    {
     "title": "Team 1 Revives and Deaths",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "rawSql": "SELECT COUNT(*) AS \"Team 1 Deaths\"\nFROM DBLog_Deaths\nWHERE \n`server` = $SERVER AND\n`match` = $MATCH AND\nvictimTeamID = 1;"
      },
      {
       "rawSql": "SELECT COUNT(*) AS \"Team 1 Revives\"\nFROM DBLog_Revives\nWHERE\n`server` = $SERVER AND\n`match` = $MATCH AND\nvictimTeamID = 1;"
      }
     ]
    },
    {
     "title": "Team 1 Kills and Incaps",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "dataset": "squadjs",
       "rawSql": "SELECT COUNT(*) AS \"Team 1 Kills\"\nFROM DBLog_Deaths\nWHERE `server` = $SERVER  AND\n      `match` = $MATCH AND\n      teamkill = 0 AND\n      attackerTeamID = 1"
      },
      {
       "rawSql": "SELECT COUNT(*) AS \"Team 1 Wounds\"\nFROM DBLog_Revives\nWHERE `server` = $SERVER  AND\n      `match` = $MATCH AND\n      teamkill = 0 AND\n      victimTeamID = 2"
      }
     ]
    },
    {
     "title": "Team 2 Revives and Deaths",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "rawSql": "SELECT COUNT(*) AS \"Team 2 Deaths\"\nFROM DBLog_Deaths\nWHERE \n`server` = $SERVER AND\n`match` = $MATCH AND\nvictimTeamID = 2;"
      },
      {
       "rawSql": "SELECT COUNT(*) AS \"Team 2 Revives\"\nFROM DBLog_Revives\nWHERE\n`server` = $SERVER AND\n`match` = $MATCH AND\nvictimTeamID = 2;"
      }
     ]
    },
    {
     "title": "Team 2 Kills and Incaps",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "dataset": "squadjs",
       "rawSql": "SELECT COUNT(*) AS \"Team 2 Kills\"\nFROM DBLog_Deaths\nWHERE `server` = $SERVER  AND\n      `match` = $MATCH AND\n      teamkill = 0 AND\n      attackerTeamID = 2"
      },
      {
       "rawSql": "SELECT COUNT(*) AS \"Team 2 Wounds\"\nFROM DBLog_Revives\nWHERE `server` = $SERVER  AND\n      `match` = $MATCH AND\n      teamkill = 0 AND\n      victimTeamID = 1"
      }
     ]
    }
   ]
  },
  { "title": "Score Board", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Team 1",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "select lastName, killt.squadID, kills, deaths, incaps\nfrom (\n    select attacker, attackerTeamID as teamID, attackerSquadID as squadID, count(*) as kills\n    from DBLog_Deaths\n    where `match`=$MATCH and teamkill != 1\n    group by attacker\n) as killt join (\n    select victim, attackerTeamID as teamID, attackerSquadID as squadID, count(*) as deaths\n    from DBLog_Deaths\n    where `match`=$MATCH and teamkill != 1\n    group by victim\n) as deatht on killt.attacker=deatht.victim join (\n    select attacker, attackerTeamID as teamID, attackerSquadID as squadID, count(*) as incaps\n    from DBLog_Wounds\n    where `match`=$MATCH and teamkill != 1\n    group by attacker\n) as woundt on killt.attacker=woundt.attacker join DBLog_SteamUsers on killt.attacker=DBLog_SteamUsers.steamID\nwhere killt.teamID=1\norder by squadID, kills desc, lastName"
    }
   ]
  },
  {
   "title": "Team 2",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "rawSql": "select lastName, killt.squadID, kills, deaths, incaps\nfrom (\n    select attacker, attackerTeamID as teamID, attackerSquadID as squadID, count(*) as kills\n    from DBLog_Deaths\n    where `match`=$MATCH and teamkill != 1\n    group by attacker\n) as killt join (\n    select victim, attackerTeamID as teamID, attackerSquadID as squadID, count(*) as deaths\n    from DBLog_Deaths\n    where `match`=$MATCH and teamkill != 1\n    group by victim\n) as deatht on killt.attacker=deatht.victim join (\n    select attacker, attackerTeamID as teamID, attackerSquadID as squadID, count(*) as incaps\n    from DBLog_Wounds\n    where `match`=$MATCH and teamkill != 1\n    group by attacker\n) as woundt on killt.attacker=woundt.attacker join DBLog_SteamUsers on killt.attacker=DBLog_SteamUsers.steamID\nwhere killt.teamID=2\norder by squadID, kills desc, lastName"
    }
   ]
  }
 ]
}