{
 "title": "Players Online",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Admins Online",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT lastName as 'Player',\r\n  player as 'Steam ID',\r\n  startTime as 'Logged on at'\r\nFROM DBLog_PlayerTimes JOIN DBLog_SteamUsers on (DBLog_PlayerTimes.player = DBLog_SteamUsers.steamID)\r\nWHERE endTime is null and\r\n  startTime is not null and\r\n  player is not null and\r\n  lastName regexp '\\\\{ASG[a,o]\\\\}.*' and\r\n  server=1"
    }
   ]
  },
  {
   "title": "Admins Online",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT lastName as 'Player',\r\n  player as 'Steam ID',\r\n  startTime as 'Logged on at'\r\nFROM DBLog_PlayerTimes JOIN DBLog_SteamUsers on (DBLog_PlayerTimes.player = DBLog_SteamUsers.steamID)\r\nWHERE endTime is null and\r\n  startTime is not null and\r\n  player is not null and\r\n  lastName regexp '\\\\{ASG[a,o]\\\\}.*' and\r\n  server=2"
    }
   ]
  },
  {
   "title": "Vanilla Players Online",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT lastName as 'Player',\n  player as 'Steam ID',\n  startTime as 'Logged on at'\nFROM DBLog_PlayerTimes JOIN DBLog_SteamUsers on (DBLog_PlayerTimes.player = DBLog_SteamUsers.steamID)\nWHERE endTime is null and\n  startTime is not null and\n  player is not null and\n  server=1"
    }
   ]
  },
  {
   "title": "MEE Players Online",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT lastName as 'Player',\n  player as 'Steam ID',\n  startTime as 'Logged on at'\nFROM DBLog_PlayerTimes JOIN DBLog_SteamUsers on (DBLog_PlayerTimes.player = DBLog_SteamUsers.steamID)\nWHERE endTime is null and\n  startTime is not null and\n  player is not null and\n  server=2"
    }
   ]
  }
 ]
}