{
 "title": "Player Statistics",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "PLAYERID",
    "label": "Player Name",
    "query": "select steamID as __value, lastName as __text\nfrom DBLog_SteamUsers"
   },
   {
    "name": "seed",
    "label": "Include Seeding",
    "query": "no : and layerClassname not regexp '_Seed_', yes : and layerClassname is not null"
   }
  ]
 },
 "panels": [
  { "title": "Standard Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Player ID",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select lastName as 'Player Name', steamID as 'Steam ID'\nfrom DBLog_SteamUsers\nwhere steamID = $PLAYERID "
    }
   ]
  },
  {
   "title": "Kills and Deaths",
   "type": "stat",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) as Incaps\n              from DBLog_Wounds\n                       join DBLog_Matches DLM on DBLog_Wounds.`match` = DLM.id\n              where attacker = $PLAYERID\n                and victim != $PLAYERID\n                and teamkill = 0\n                and DBLog_Wounds.server != 3\n                and map != 'Jensen\\'s'\n                ${seed:value}"
    },
    {
     "rawSql": "select count(*) as Kills\n              from DBLog_Deaths\n                       join DBLog_Matches DLM on DBLog_Deaths.`match` = DLM.id\n              where attacker = $PLAYERID\n                and victim != $PLAYERID\n                and teamkill = 0\n                and DBLog_Deaths.server != 3\n                and map != 'Jensen\\'s'\n                ${seed:value}"
    },
    {
     "rawSql": "select count(*) as Fallen\n              from DBLog_Wounds\n                       join DBLog_Matches DLM on DBLog_Wounds.`match` = DLM.id\n              where victim = $PLAYERID\n                and attacker != $PLAYERID\n                and teamkill = 0\n                and DBLog_Wounds.server != 3\n                and map != 'Jensen\\'s'\n                ${seed:value}"
    },
    {
     "rawSql": "select count(*) as Deaths\n              from DBLog_Deaths\n                       join DBLog_Matches DLM on DBLog_Deaths.`match` = DLM.id\n              where victim = $PLAYERID\n                and attacker != $PLAYERID\n                and teamkill = 0\n                and DBLog_Deaths.server != 3\n                and map != 'Jensen\\'s'\n                ${seed:value}"
    },
    { "expression": "$Incaps/$Fallen", "type": "math" },
    { "expression": "$Incaps/$Deaths", "type": "math" },
    { "expression": "$Kills/$Deaths", "type": "math" }
   ]
  },
  {
   "title": "Weapon Usage (Incaps) (Top 25)",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select weapon as 'Weapon', count(*) as 'Incaps'\nfrom DBLog_Wounds join DBLog_Matches DLM on DBLog_Wounds.`match` = DLM.id\nwhere attacker = $PLAYERID\n  and teamkill = 0\n  and DBLog_Wounds.server != 3\n  and map != 'Jensen\\'s'\n  ${seed:value}\ngroup by weapon\norder by Incaps desc"
    }
   ]
  },
  {
   "title": "Kills and Deaths per Match",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select incaps/matches as 'Incaps', kills/matches as 'Kills', downed/matches as 'Fallen', deaths/matches as 'Deaths'\nfrom (select lastname,\n             steamID,\n             (select count(*)\n              from DBLog_Wounds\n                       join DBLog_Matches DLM on DBLog_Wounds.`match` = DLM.id\n              where attacker = $PLAYERID\n                and victim != $PLAYERID\n                and teamkill = 0\n                and DBLog_Wounds.server != 3\n                and map != 'Jensen\\'s'\n                ${seed:value}) as incaps,\n             (select count(*)\n              from DBLog_Deaths\n                       join DBLog_Matches DLM on DBLog_Deaths.`match` = DLM.id\n              where attacker = $PLAYERID\n                and victim != $PLAYERID\n                and teamkill = 0\n                and DBLog_Deaths.server != 3\n                and map != 'Jensen\\'s'\n                ${seed:value}) as kills,\n             (select count(*)\n              from DBLog_Wounds\n                       join DBLog_Matches DLM on DBLog_Wounds.`match` = DLM.id\n              where victim = $PLAYERID\n                and attacker != $PLAYERID\n                and teamkill = 0\n                and DBLog_Wounds.server != 3\n                and map != 'Jensen\\'s'\n                ${seed:value}) as downed,\n             (select count(*)\n              from DBLog_Deaths\n                       join DBLog_Matches DLM on DBLog_Deaths.`match` = DLM.id\n              where victim = $PLAYERID\n                and attacker != $PLAYERID\n                and teamkill = 0\n                and DBLog_Deaths.server != 3\n                and map != 'Jensen\\'s'\n                ${seed:value}) as deaths,\n            (select count(*)\n           from (select D.id\n           from DBLog_Wounds join DBLog_Matches D on DBLog_Wounds.`match` = D.id\n           where (victim = $PLAYERID or attacker = $PLAYERID)\n           and D.server != 3\n           and map != 'Jensen\\'s'\n           ${seed:value}\n           group by D.id) as matches\n           ) as matches\n      from DBLog_SteamUsers\n      where steamID = $PLAYERID\n      ) as psr"
    }
   ]
  },
  {
   "title": "Amount Played",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) as Matches\n           from (select D.id\n           from DBLog_Wounds join DBLog_Matches D on DBLog_Wounds.`match` = D.id\n           where (victim = $PLAYERID or attacker = $PLAYERID)\n           and D.server != 3\n           and map != 'Jensen\\'s'\n           ${seed:value}\n           group by D.id) as matches"
    },
    {
     "rawSql": "select sum(time_to_sec(timediff(ifnull(endTime,now()),startTime))/3600) as 'Total Hours'\nfrom DBLog_PlayerTimes\nwhere server != 3 \n  and player = $PLAYERID\nlimit 1"
    },
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Revives and Deaths",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select revives as 'Revives', revived as 'Revived', (revives/deaths) as 'Revives per Death', (revived/deaths) as 'Revived per Death', revives/matches as 'Revives per Match', revived/matches as 'Revived per Match'\nfrom (select lastname,\n             steamID,\n             (select count(*)\n              from DBLog_Revives join DBLog_Matches DLM on DBLog_Revives.`match` = DLM.id\n              where reviver = $PLAYERID\n                and teamkill = 0\n                and DLM.server != 3\n                and map != 'Jensen\\'s'\n                ${seed:value}) as revives,\n             (select count(*)\n              from DBLog_Revives join DBLog_Matches DLM on DBLog_Revives.`match` = DLM.id\n              where victim = $PLAYERID\n                and teamkill = 0\n                and DLM.server != 3\n                and map != 'Jensen\\'s'\n                ${seed:value}) as revived,\n             (select count(*)\n              from DBLog_Deaths\n                       join DBLog_Matches DLM on DBLog_Deaths.`match` = DLM.id\n              where victim = $PLAYERID\n                and attacker != $PLAYERID\n                and teamkill = 0\n                and DBLog_Deaths.server != 3\n                and map != 'Jensen\\'s'\n                ${seed:value}) as deaths,\n            (select count(*)\n           from (select D.id\n           from DBLog_Wounds join DBLog_Matches D on DBLog_Wounds.`match` = D.id\n           where (victim = 76561198221715432 or attacker = 76561198221715432)\n           and D.server != 3\n           and map != 'Jensen\\'s'\n           ${seed:value}\n           group by D.id) as matches\n           ) as matches\n      from DBLog_SteamUsers\n      where steamID = $PLAYERID\n      ) as psr"
    }
   ]
  },
  {
   "title": "TKs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 18, "x": 4, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select tks as 'TKs', tked as 'TKed', (tks/deaths) as 'TKs per Death', (tked/deaths) as 'TKed per Death', tks/matches as 'TKs per Match', tked/matches as 'TKed per Match'\nfrom (select lastname,\n             steamID,\n             (select count(*)\n              from DBLog_Wounds join DBLog_Matches DLM on DBLog_Wounds.`match` = DLM.id\n              where attacker = $PLAYERID\n                and victim != $PLAYERID\n                and teamkill = 1\n                and DLM.server != 3\n                and map != 'Jensen\\'s'\n                ${seed:value}) as tks,\n             (select count(*)\n              from DBLog_Wounds join DBLog_Matches DLM on DBLog_Wounds.`match` = DLM.id\n              where victim = $PLAYERID\n                and attacker != $PLAYERID\n                and teamkill = 1\n                and DLM.server != 3\n                and map != 'Jensen\\'s'\n                ${seed:value}) as tked,\n             (select count(*)\n              from DBLog_Deaths\n                       join DBLog_Matches DLM on DBLog_Deaths.`match` = DLM.id\n              where victim = $PLAYERID\n                and teamkill = 0\n                and DBLog_Deaths.server != 3\n                and map != 'Jensen\\'s'\n                ${seed:value}) as deaths,\n            (select count(*)\n           from (select D.id\n           from DBLog_Wounds join DBLog_Matches D on DBLog_Wounds.`match` = D.id\n           where (victim = 76561198221715432 or attacker = 76561198221715432)\n           and D.server != 3\n           and map != 'Jensen\\'s'\n           ${seed:value}\n           group by D.id) as matches\n           ) as matches\n      from DBLog_SteamUsers\n      where steamID = $PLAYERID\n      ) as psr"
    }
   ]
  },
  {
   "title": "Pie Charts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Incaps (Top 25)",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 4, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select victimName as 'Player', count(*) as 'Incaps'\nfrom DBLog_Wounds join DBLog_Matches DLM on DBLog_Wounds.`match` = DLM.id\nwhere attacker = $PLAYERID \n  and victim is not null\n  and victim != $PLAYERID \n  and teamkill = 0\n  and DBLog_Wounds.server != 3\n  and map != 'Jensen\\'s'\n  ${seed:value}\ngroup by victim\norder by Incaps desc"
      }
     ]
    },
    {
     "title": "Kills (Top 25)",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 4, "x": 4, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select victimName as 'Player', count(*) as 'Kills'\nfrom DBLog_Deaths join DBLog_Matches DLM on DBLog_Deaths.`match` = DLM.id\nwhere attacker = $PLAYERID\n  and victim is not null\n  and victim != $PLAYERID\n  and teamkill = 0\n  and DLM.server != 3\n  and map != 'Jensen\\'s'\n  ${seed:value}\ngroup by victim\norder by Kills desc"
      }
     ]
    },
    {
     "title": "Fallen (Top 25)",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 4, "x": 8, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select attackerName as 'Player', count(*) as 'Fallen'\nfrom DBLog_Wounds join DBLog_Matches DLM on DBLog_Wounds.`match` = DLM.id\nwhere victim = $PLAYERID\n  and attacker != $PLAYERID\n  and teamkill = 0\n  and DLM.server != 3\n  and map != 'Jensen\\'s'\n  ${seed:value}\ngroup by attacker\norder by Fallen desc"
      }
     ]
    },
    {
     "title": "Deaths (Top 25)",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 4, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select attackerName as 'Player', count(*) as 'Kills'\nfrom DBLog_Deaths join DBLog_Matches DLM on DBLog_Deaths.`match` = DLM.id\nwhere victim = $PLAYERID\n  and attacker != $PLAYERID\n  and teamkill = 0\n  and DLM.server != 3\n  and map != 'Jensen\\'s'\n  ${seed:value}\ngroup by attacker\norder by Kills desc"
      }
     ]
    },
    {
     "title": "Revives (Top 25)",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 4, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select victimName as 'Player', count(*) as 'Revives'\nfrom DBLog_Revives join DBLog_Matches DLM on DBLog_Revives.`match` = DLM.id\nwhere victim != $PLAYERID \n  and reviver = $PLAYERID \n  and teamkill != 1\n  and DLM.server != 3\n  and map != 'Jensen\\'s'\n  ${seed:value}\ngroup by victim\norder by Revives desc"
      }
     ]
    },
    {
     "title": "Revived (Top 25)",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 4, "x": 4, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select reviverName as 'Player', count(*) as 'Revived'\nfrom DBLog_Revives join DBLog_Matches DLM on DBLog_Revives.`match` = DLM.id\nwhere victim = $PLAYERID \n  and reviver != $PLAYERID \n  and teamkill != 1\n  and DLM.server != 3\n  and map != 'Jensen\\'s'\n  ${seed:value}\ngroup by reviver\norder by Revived desc"
      }
     ]
    },
    {
     "title": "TKs (Top 25)",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 4, "x": 8, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select victimName as 'Player', count(*) as 'TKs'\nfrom DBLog_Wounds join DBLog_Matches DLM on DBLog_Wounds.`match` = DLM.id\nwhere victim != $PLAYERID \n  and attacker = $PLAYERID \n  and teamkill = 1\n  and DLM.server != 3\n  and map != 'Jensen\\'s'\n  ${seed:value}\ngroup by victim\norder by TKs desc"
      }
     ]
    },
    {
     "title": "TKed (Top 25)",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 4, "x": 12, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select attackerName as 'Player', count(*) as 'TKed'\nfrom DBLog_Wounds join DBLog_Matches DLM on DBLog_Wounds.`match` = DLM.id\nwhere victim = $PLAYERID \n  and attacker != $PLAYERID \n  and teamkill = 1\n  and DLM.server != 3\n  and map != 'Jensen\\'s'\n  ${seed:value}\ngroup by attacker\norder by TKed desc"
      }
     ]
    }
   ]
  },
  { "title": "Time Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "KDR / IPF",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "select time, kills/deaths as KDR\nfrom (\nselect time, sum(deaths) over (order by time) as deaths, sum(kills) over (order by time) as kills\nfrom\n(select DBLog_Deaths.time,\n        if(victim = $PLAYERID, 1, 0)   as deaths,\n        if(attacker = $PLAYERID, 1, 0) as kills\n from DBLog_Deaths\n          join DBLog_Matches DLM on DBLog_Deaths.`match` = DLM.id\n where ((attacker != $PLAYERID \n     and victim = $PLAYERID) or\n        (attacker = $PLAYERID \n            and victim != $PLAYERID))\n   and teamkill = 0\n   and DBLog_Deaths.server != 3\n   and map != 'Jensen\\'s') as kdtime) as kdsum"
    },
    {
     "rawSql": "select time, kills/deaths as IPF\nfrom (\nselect time, sum(deaths) over (order by time) as deaths, sum(kills) over (order by time) as kills\nfrom\n(select DBLog_Wounds.time,\n        if(victim = $PLAYERID, 1, 0)   as deaths,\n        if(attacker = $PLAYERID, 1, 0) as kills\n from DBLog_Wounds\n          join DBLog_Matches DLM on DBLog_Wounds.`match` = DLM.id\n where ((attacker != $PLAYERID \n     and victim = $PLAYERID) or\n        (attacker = $PLAYERID \n            and victim != $PLAYERID))\n   and teamkill = 0\n   and DBLog_Wounds.server != 3\n   and map != 'Jensen\\'s') as kdtime) as kdsum"
    }
   ]
  }
 ]
}