{
 "title": "Server Overview",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "SERVER",
    "query": "SELECT id as __value, trim(leading '[ASG] Asgard Eternal | ' from name) as __text\nFROM DBLog_Servers"
   }
  ]
 },
 "panels": [
  {
   "title": "Server Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select (\n      select trim(leading '[ASG] Asgard Eternal | ' from name)\n      from DBLog_Servers\n      where DBLog_Servers.id = $SERVER\n      limit 1\n      ) as 'Server Name',\n    layer,startTime, id, (\n    select players\n    from DBLog_PlayerCounts\n    where DBLog_PlayerCounts.server=$SERVER\n    order by DBLog_PlayerCounts.id desc\n    limit 1\n    ) as players, (\n    select publicQueue\n    from DBLog_PlayerCounts\n    where DBLog_PlayerCounts.server=$SERVER\n    order by DBLog_PlayerCounts.id desc\n    limit 1\n    ) as queue,(\n    select avg(players)\n    from DBLog_PlayerCounts\n    where DBLog_PlayerCounts.server=$SERVER and\n          `match`=DBLog_Matches.id\n    ) as 'avg players',(\n    select avg(publicQueue)\n    from DBLog_PlayerCounts\n    where DBLog_PlayerCounts.server=$SERVER and\n          `match`=DBLog_Matches.id\n    ) as 'avg queue'\nfrom DBLog_Matches\nwhere\n    endTime is null and\n    server=$SERVER"
    }
   ]
  },
  {
   "title": "Player Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time,\r\n  players as \"Player Count\"\r\nFROM DBLog_PlayerCounts\r\nWHERE\r\n  server=$SERVER\r\nGROUP BY 1\r\nORDER BY time DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Player Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time,\r\n  players as \"player_count\",\r\n  publicQueue as \"public_queue\"\r\nFROM DBLog_PlayerCounts\r\nWHERE\r\n  $__timeFilter(time) AND\r\n  server=$SERVER\r\nGROUP BY 1\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Tick Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time,\r\n  tickRate\r\nFROM DBLog_TickRates\r\nWHERE\r\n  server=$SERVER\r\nORDER BY time DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time,\r\n  tickRate as \"tick rate\"\r\nFROM DBLog_TickRates\r\nWHERE\r\n  $__timeFilter(time) and\r\n  server=$SERVER\r\nORDER BY time DESC"
    }
   ]
  }
 ]
}